### PR TITLE
6 setup front end part of login page

### PR DESCRIPTION
**Pull request by S-Stanley**
PR https://github.com/thi-nguy/matcha/pull/5 should be merged before this one.

The goal of this PR is to setup the frontend part of the login page, since the api is not up yet.

FIGMA:

image

REACT:

Capture d’écran 2023-11-18 à 10 06 25

### CODE REVIEW

**Comment by thi-nguy** [comment]
Thank you for your work. Just one thing that I think you divided the page into too small components. Before I made that too but apparently if the components are not reusable, we don't need to create new one. I'll ask more my senior at work on this, like is there any patterns or other reasons behind this.

**Comment by thi-nguy** [comment]
Yeah so I asked them, rule of thumb is you cut them into smaller components if they are reusable, or your component just too big. 
Maybe you can put all small components into one page: Login page?

**Comment by S-Stanley** [comment]
@thi-nguy, well, it's actually depended on people, most of them follow the [rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)).

Most component there will be used in signup page (https://github.com/thi-nguy/matcha/pull/9/files) but also in profile edit, recover password and such as show on the figma (https://www.figma.com/file/Fk3uNc9sXpJAGlf6RVKOgA/Matcha?type=design&node-id=0-1&mode=design&t=29tGiSrUDxyJD0bN-0)

If you insist I will do it, but in my opinion it's a waste of time

**Comment by thi-nguy** [comment]
No it's just a review for your consideration, you have all the right to apply it or not. I'll approve it. If you want to keep them, you can rebase and merge. If not you can push another commit :)

**Comment by S-Stanley** [comment]
@thi-nguy I am pretty sure these components will be used multiple times. You can merge

**Review by thi-nguy — APPROVED** [review]

**Pull request merged**
